### ISSUE TITLE
مشکل حذف کردن آلارم‌ها

### ISSUE THREAD

**Issue by persenger** [Mohammadreza-Mohammadi/Basamad#30]
آلارم‌ها حذف نمی‌شوند. با فشردن دکمه‌ی ضربدر پیغام خطای زیر رخ می‌دهد:
DR650
![Screenshot 2023-02-19 152921](https://user-images.githubusercontent.com/125562600/219947709-52029d6d-6189-4b17-8f1a-fd9b41aadbbb.jpg)

**Comment by Mohammadreza-Mohammadi** [comment]
مشکل برطرف گردید.
