### ISSUE TITLE
نمای کوره اشکال دارد

### ISSUE THREAD

**Issue by persenger** [Mohammadreza-Mohammadi/Basamad#32]
نمای کوره‌ها حتی بعد از تقسیم‌بندی به قمیرهای رخ یک و دو درست تنظیم نمی‌شود. قبلاً هادیان این مورد را نشان می‌داد و حالا رحمت‌آباد.
![Screenshot 2023-02-19 170459](https://user-images.githubusercontent.com/125562600/219951628-38ecb525-8048-425f-ae15-6a1e105a7921.jpg)

**Comment by persenger** [comment]
رحمت‌آباد در حال حاضر فقط رخ ۲ دارد که همه‌ی قمیرها در آن است. 
![Screenshot 2023-02-19 170905](https://user-images.githubusercontent.com/125562600/219951890-2573f944-720b-4cb2-a098-5c0b6139d9ab.jpg)

**Comment by Mohammadreza-Mohammadi** [comment]
زمانی که برنامه در کارخانه اجرا شود و اولین اطلاعات بارگذاری شود این ظاهر درست میشود.
چون برنامه درکارخانه در حال اجرا نیست این اتفاق افتاده است.
لطفا بعد از بررسی برنامه در کارخانه این مورد بررسی شود.
