### ISSUE TITLE
اطلاعات کوره‌ی ۱ هادیان غلط است

### ISSUE THREAD

**Issue by persenger** [Mohammadreza-Mohammadi/Basamad#33]
کوره‌ی ۱ هادیان اطلاعات نادرستی بارگذاری می‌کند،دماها را به‌صورت نادرست نشان می‌دهد.

**Comment by Mohammadreza-Mohammadi** [comment]
کوره 1 هادیان به نظر در حال اجرا نیست برنامه در حال اجرا نیست. آخرین تاریخ بروزرسانی  کوره  1401/10/25
