### ISSUE TITLE
نور شهریار کجاست؟

### ISSUE THREAD

**Issue by persenger** [Mohammadreza-Mohammadi/Basamad#34]
کارخانه‌ی نور شهریار غیب شده است و تایل آن دیده نمی‌شود!
این اتفاق قبلاً برای کیمیا هم افتاده است و هنوز رفع نشده.

**Comment by Mohammadreza-Mohammadi** [comment]
مشکل مرتفع شد.
فقط نور شهریار هم برنامه در حال اجرا نیست چون اخرین تاریخ بروز رسانی  1401/10/15
