### ISSUE TITLE
جابه‌جایی‌های کارخانه‌ی دادخواه

### ISSUE THREAD

**Issue by persenger** [Mohammadreza-Mohammadi/Basamad#36]
جابه‌جایی‌های کوره‌های 1 و 3 دادخواه نمایش داده نمی‌شود. 
![Screenshot 2023-02-20 151242](https://user-images.githubusercontent.com/125562600/220097405-e3b9d39d-5d65-410e-91a8-dcd994597335.jpg)

**Comment by Mohammadreza-Mohammadi** [comment]
رجوع شود به #38
