### ISSUE TITLE
کوره‌ی یکم دادخواه خواب است؟

### ISSUE THREAD

**Issue by persenger** [Mohammadreza-Mohammadi/Basamad#37]
در کوره‌ی یکم دادخواه فعالیتی مشاهده نمی‌شود، در حالی که کوره روشن است.
![Screenshot 2023-02-20 151658](https://user-images.githubusercontent.com/125562600/220098088-671faba8-377f-4a42-9196-ba3f8345d1b0.jpg)

**Comment by Mohammadreza-Mohammadi** [comment]
#36
