### ISSUE TITLE
اطلاعات کوره‌ی سوم دادخواه نادرست است

### ISSUE THREAD

**Issue by persenger** [Mohammadreza-Mohammadi/Basamad#38]
کوره‌ی سوم دادخواه:
دی‌آرتی‌های شگفت‌انگیز
عدد پخت غایب است
دماها نمی‌آید

باقی این غزل را ای مطرب ظریف
زین‌سان همی‌شمار که زین‌سانم آرزوست

**Comment by Mohammadreza-Mohammadi** [comment]
دادخواه به نظر اصلا برنامه در حال اجرا نیست چون آخرین بروزرسانی مربوط به 1401/10/07
