### ISSUE TITLE
تکنو بالا نمی‌آید

### ISSUE THREAD

**Issue by persenger** [Mohammadreza-Mohammadi/Basamad#40]
![Screenshot 2023-02-20 160610](https://user-images.githubusercontent.com/125562600/220109811-659282e9-bdb8-4b05-b330-d7a6224601c1.jpg)

**Comment by Mohammadreza-Mohammadi** [comment]
در قسمت مدیریت کارخانه ها تکنو مشاهده نشد.
احتمال دارد که کارخانه را ایجاد کرده اید و ایجاد تایلها را زده اید و ذخیره و بستن را نزده اید.
حتما بعداز ایجاد کارخانه یا کوره یک بار بررسی شود که درست ایجاد شده اند یا نه و سپس اقدام به انجام مراحل بعد شود.
